# Generated by Django 2.2.3 on 2022-05-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220425_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='state',
            field=models.IntegerField(choices=[(0, 'Undone'), (1, 'Doing'), (2, 'Done')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default_user_icon.jpg', upload_to='images/%Y%m/%d/icons'),
        ),
    ]
