# Generated by Django 2.2.28 on 2022-05-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220523_2104'),
        ('core', '0005_evaluation'),
    ]

    operations = [
    ]
