# Generated by Django 2.2.28 on 2022-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20220531_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='orikeywords',
            field=models.CharField(default='', max_length=200),
        ),
    ]
